/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u         /*!<@brief Input Buffer Enable: Enables */
#define PCR_PE_pe1 0x01u           /*!<@brief Pull Enable: Enables */
#define PCR_SRE_sre0 0x00u         /*!<@brief Slew Rate Enable: Fast */
#define PORT2_PCR5_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR7_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT3_12 (number 38), BIN1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BIN1_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_BIN1_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_BIN1_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_BIN1_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BIN1_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BIN1_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BIN1_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT3_13 (number 37), BIN2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BIN2_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_BIN2_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_BIN2_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_BIN2_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BIN2_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BIN2_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BIN2_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT2_5 (number 19), AIN2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_AIN2_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_AIN2_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_AIN2_GPIO_PIN 5U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_AIN2_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_AIN2_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_AIN2_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_AIN2_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_0 (number 46), AIN1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_AIN1_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_AIN1_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_AIN1_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_AIN1_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_AIN1_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_AIN1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_AIN1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT2_7 (number 21), STBY_DRIVER
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_STBY_DRIVER_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_STBY_DRIVER_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_STBY_DRIVER_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_STBY_DRIVER_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_STBY_DRIVER_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_STBY_DRIVER_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STBY_DRIVER_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_6 (number 44), PWMA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PWMA_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PWMA_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PWMA_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_8 (number 42), PWMB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PWMB_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PWMB_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PWMB_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
